baseURL = "https://www.xin1t.com/blog/"
languageCode = "zh-Hans"
title = "大师兄's Blog"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
#disqusShortname = "disqus_shortname"

# Google Analytics UA number
# googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"

#[[menu.main]]
#  name = "作品"
#  weight = 20
#  identifier = "works"
#  url = "https://github.com/xinfeng-tech"

[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "大师兄"
  bg = "images/grey-prism.svg"
  avatar = "images/avatar.png"
  seotitle = "大师兄的博客"
  subtitle = "~ Front End Engineer ~"
  description = "这里是 @大师兄 的个人博客，记录他在互联网新世界探索的点点滴滴 This is qianxinfeng's personal blog, recording his exploration in the Internet industry."
  paginate = 10

  # Choose your social networks
  email = "airic1991@gmail.com"
  github = "xinfeng-tech"
  zhihu = "qianxinfeng"
  weibo = "shaguawb"
  # wechat= "images/wechat-qrcode.png"  # Replace with your wechat qrcode image
  #twitter = "twitter_username"
  #linkedin = "linkedin_username"
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"

  # douban = "douban_username"
  # bilibili = "bilibili_id_number"
  # stackoverflow = "laozhu"
  # codesandbox = "melaozhu"
  # npm = "laozhu"
  # reddit = "melaozhu"

  # Overrid theme styles in this file
  # customStyle = "styles/custom.scss"

  # Changyan Comments (China Only)
  #changyan = false
  #changyanId = "cyt3toRiB"
  #changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  #googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  #msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  baiduSiteVerification = "Ao1cb94PkK"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"
